font_family "Iosevka"
font_size 13
disable_ligatures no

window_padding_width 10
window_padding_height 10

cursor_style block
cursor_blink_interval 0
cursor_color #707070
cursor_text_color #1a1a1a

background #1a1a1a
foreground #e0e0e0
selection_background #2a2a2a
selection_foreground #e0e0e0
color0 #1a1a1a
color1 #909090
color2 #707070
color3 #808080
color4 #606060
color5 #707070
color6 #787878
color7 #d0d0d0
color8 #404040
color9 #a0a0a0
color10 #808080
color11 #909090
color12 #707070
color13 #808080
color14 #888888
color15 #f0f0f0

scrollback_lines 10000
repaint_delay 10
input_delay 3
sync_to_monitor yes

