## HYPRIDLE — Hyprland 0.54

general {
    lock_cmd            = pidof hyprlock || hyprlock
    before_sleep_cmd    = loginctl lock-session
    after_sleep_cmd     = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 4 min — bajar brillo al 20%
listener {
    timeout    = 240
    on-timeout = brightnessctl -s set 20%
    on-resume  = brightnessctl -r
}

# 8 min — bloquear pantalla
listener {
    timeout    = 480
    on-timeout = loginctl lock-session
}

# 9 min — apagar pantalla
listener {
    timeout    = 540
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# 3 horas — apagar sistema
listener {
    timeout    = 10800
    on-timeout = systemctl poweroff
}
